# Generated by Django 5.0.4 on 2024-09-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nom', models.CharField(db_column='nom', max_length=255)),
                ('prenom', models.CharField(db_column='prenom', max_length=100)),
                ('adresse', models.CharField(db_column='adresse', max_length=100)),
            ],
            options={
                'db_table': 'utilisateur',
            },
        ),
    ]
