name: Django-CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
        
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
        
      - name: Run Tests
        run: |
          python manage.py test
        
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          echo "[dev.hpgp6881.mywhc.ca]:27,[144.217.129.53]:27 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEVeUqD+taHDeMNtEKHgz0z2xeGv5f44JAqnsTiPmGemoOV9ImZq+TyuInpk9uooWzrRs16BetFae3N4/A9uWSo=" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
            rsync -avz --delete -e 'ssh -p 27' ./ hpgp6881@dev.hpgp6881.mywhc.ca:/home/hpgp6881/dev.hpgp6881.mywhc.ca/