name: Deploy to Subdomain via FTP

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.2'  # Spécifiez votre version de Python ici

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Upload files via FTP
        uses: SamKirkland/FTP-Upload@v1.1.0
        with:
          server: app.gradasbl.org
          username: pftckq  # Votre nom d'utilisateur FTP
          password: ${{ secrets.FTP_PASSWORD }}  # Le mot de passe FTP
          local-dir: .
          server-dir: /home/pftckq/app.gradasbl.org/  # Chemin vers votre sous-domaine