name: Django CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.2]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
        
      - name: Run Tests
        run: |
          python manage.py test
        
      - name: Install lftp
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp
      
      - name: Deploy to Server via FTP
        run: |
            lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ftp://app.gradasbl.org <<EOF
            mirror -R ./ /home/pftckq/public_html/
            bye
            EOF
            